### ISSUE TITLE
AttributeError: module 'asyncua.ua' has no attribute 'TePartSeparationState'

### ISSUE THREAD

**Issue by JohannesM24** [TRUMPF-IoT/OpcUaMachineTools#2]
Hi guys,

when trying to run the PythonMachineDemoServer.py I get above error. My python version is 3.8.3 and asyncua is 0.9.90. See the full output from running `py .\PythonMachineDemoServer.py` 

```
Deprecated since spec 1.04, call load_data_type_definitions


@dataclass
class TsLaserMetalDepositionTechnology:

    '''
    TsLaserMetalDepositionTechnology structure autogenerated from xml
    '''

    ViewerName:ua.CharArray = b''
    KeyPart:ua.CharArray = b''
    CustomerTable:ua.Int32 = 0
    LaserType:ua.CharArray = b''
    ContourWidth:ua.Double = 0
    LayerThickness:ua.Double = 0
    LineOverlap:ua.Int32 = 0
    BaseMaterial:ua.CharArray = b''
    PowderType1:ua.CharArray = b''
    PowderType2:ua.CharArray = b''
    PowderType3:ua.CharArray = b''
    NozzleDistance:ua.Double = 0
    NozzleType:ua.CharArray = b''
    Comment:ua.CharArray = b''
    BasicFeed:ua.Double = 0
    BasicAcceleration:ua.Double = 0
    BasicFrequency:ua.Double = 0
    BasicPeakPower:ua.Double = 0
    BasicPower:ua.Double = 0
    BasicSpotDiameter:ua.Double = 0
    BasicTopHatActive:ua.Int32 = 0
    PowderAmplitudeComment1:ua.CharArray = b''
    PowderAmplitudeComment2:ua.CharArray = b''
    PowderAmplitudeComment3:ua.CharArray = b''
    NozzleGasTypeComment:ua.CharArray = b''
    CarriergasTypeComment1:ua.CharArray = b''
    CarriergasTypeComment2:ua.CharArray = b''
    CarriergasTypeComment3:ua.CharArray = b''
    PrePurgePowderTime:ua.Double = 0
    CarrierGasFlow1:ua.Double = 0
    CarrierGasFlow2:ua.Double = 0
    CarrierGasFlow3:ua.Double = 0
    CarrierGasFlow4:ua.Double = 0
    PowderAmplitude1:ua.Int32 = 0
    PowderAmplitude2:ua.Int32 = 0
    PowderAmplitude3:ua.Int32 = 0
    PowderAmplitude4:ua.Int32 = 0
    PrePurgeNozzleGasTime:ua.Double = 0
    PostPurgeNozzleGasTime:ua.Double = 0
    NozzleGasFlow:ua.Double = 0
    FeedInterpolationPointsCount:ua.Int32 = 0
    FeedTopHatActive:ua.Int32 = 0
    FeedVelocity1:ua.Double = 0
    FeedVelocity2:ua.Double = 0
    FeedVelocity3:ua.Double = 0
    FeedVelocity4:ua.Double = 0
    FeedVelocity5:ua.Double = 0
    FeedVelocity6:ua.Double = 0
    FeedVelocity7:ua.Double = 0
    FeedVelocity8:ua.Double = 0
    FeedVelocity9:ua.Double = 0
    FeedPower1:ua.Double = 0
    FeedPower2:ua.Double = 0
    FeedPower3:ua.Double = 0
    FeedPower4:ua.Double = 0
    FeedPower5:ua.Double = 0
    FeedPower6:ua.Double = 0
    FeedPower7:ua.Double = 0
    FeedPower8:ua.Double = 0
    FeedPower9:ua.Double = 0
    FeedSpotDiameter1:ua.Double = 0
    FeedSpotDiameter2:ua.Double = 0
    FeedSpotDiameter3:ua.Double = 0
    FeedSpotDiameter4:ua.Double = 0
    FeedSpotDiameter5:ua.Double = 0
    FeedSpotDiameter6:ua.Double = 0
    FeedSpotDiameter7:ua.Double = 0
    FeedSpotDiameter8:ua.Double = 0
    FeedSpotDiameter9:ua.Double = 0
    DistanceInterpolationPointsCount:ua.Int32 = 0
    DistanceTopHatActive:ua.Int32 = 0
    DistanceSP1:ua.Double = 0
    DistanceSP2:ua.Double = 0
    DistanceSP3:ua.Double = 0
    DistanceSP4:ua.Double = 0
    DistanceSP5:ua.Double = 0
    DistanceSP6:ua.Double = 0
    DistanceSP7:ua.Double = 0
    DistanceSP8:ua.Double = 0
    DistanceSP9:ua.Double = 0
    DistancePower1:ua.Double = 0
    DistancePower2:ua.Double = 0
    DistancePower3:ua.Double = 0
    DistancePower4:ua.Double = 0
    DistancePower5:ua.Double = 0
    DistancePower6:ua.Double = 0
    DistancePower7:ua.Double = 0
    DistancePower8:ua.Double = 0
    DistancePower9:ua.Double = 0
    DistanceSpotDiameter1:ua.Double = 0
    DistanceSpotDiameter2:ua.Double = 0
    DistanceSpotDiameter3:ua.Double = 0
    DistanceSpotDiameter4:ua.Double = 0
    DistanceSpotDiameter5:ua.Double = 0
    DistanceSpotDiameter6:ua.Double = 0
    DistanceSpotDiameter7:ua.Double = 0
    DistanceSpotDiameter8:ua.Double = 0
    DistanceSpotDiameter9:ua.Double = 0



@dataclass
class TsLaserTechnology:

    '''
    TsLaserTechnology structure autogenerated from xml
    '''

    LT_ALL_TAB_NAME:ua.CharArray = b''
    LT_ALL_MASCH_TYP:ua.CharArray = b''
    LT_ALL_LASER_LSTG:ua.Int32 = 0
    LT_ALL_MATERIAL:ua.CharArray = b''
    LT_ALL_MAT_DICKE:ua.Double = 0
    LT_SCH_BESCHL_RED:ua.Double = 0
    LT_SCH_BESCHL:ua.Double = 0
    LT_SCH_ECKENK_ZEIT:ua.Double = 0
    LT_SCH_GASART:ua.Int32 = 0
    LT_SCH_GASART_RED:ua.Int32 = 0
    LT_SCH_GR_SPALT:ua.Double = 0
    LT_SCH_GR_NOR_LSTG:ua.Int32 = 0
    LT_SCH_GR_NOR_TASTFR:ua.Int32 = 0
    LT_SCH_GR_NOR_GESCHW:ua.Double = 0
    LT_SCH_GR_NOR_DUESENABST:ua.Double = 0
    LT_SCH_GR_NOR_GASDRUCK:ua.Double = 0
    LT_SCH_GR_RED_LSTG:ua.Int32 = 0
    LT_SCH_GR_RED_TASTFR:ua.Int32 = 0
    LT_SCH_GR_RED_GESCHW:ua.Double = 0
    LT_SCH_GR_RED_DUESENABST:ua.Double = 0
    LT_SCH_GR_RED_GASDRUCK:ua.Double = 0
    LT_SCH_MI_SPALT:ua.Double = 0
    LT_SCH_MI_NOR_LSTG:ua.Int32 = 0
    LT_SCH_MI_NOR_TASTFR:ua.Int32 = 0
    LT_SCH_MI_NOR_GESCHW:ua.Double = 0
    LT_SCH_MI_NOR_DUESENABST:ua.Double = 0
    LT_SCH_MI_NOR_GASDRUCK:ua.Double = 0
    LT_SCH_MI_RED_LSTG:ua.Int32 = 0
    LT_SCH_MI_RED_TASTFR:ua.Int32 = 0
    LT_SCH_MI_RED_GESCHW:ua.Double = 0
    LT_SCH_MI_RED_DUESENABST:ua.Double = 0
    LT_SCH_MI_RED_GASDRUCK:ua.Double = 0
    LT_SCH_KL_SPALT:ua.Double = 0
    LT_SCH_KL_NOR_LSTG:ua.Int32 = 0
    LT_SCH_KL_NOR_TASTFR:ua.Int32 = 0
    LT_SCH_KL_NOR_GESCHW:ua.Double = 0
    LT_SCH_KL_NOR_DUESENABST:ua.Double = 0
    LT_SCH_KL_NOR_GASDRUCK:ua.Double = 0
    LT_SCH_KL_RED_LSTG:ua.Int32 = 0
    LT_SCH_KL_RED_TASTFR:ua.Int32 = 0
    LT_SCH_KL_RED_GESCHW:ua.Double = 0
    LT_SCH_KL_RED_DUESENABST:ua.Double = 0
    LT_SCH_KL_RED_GASDRUCK:ua.Double = 0
    LT_EINST_FOKUSLAGE:ua.Double = 0
    LT_EINST_NOR_ZEIT:ua.Double = 0
    LT_EINST_NOR_RAMPNR:ua.Int32 = 0
    LT_EINST_NOR_DUESENABST:ua.Double = 0
    LT_EINST_NOR_AUSBLASZEIT:ua.Double = 0
    LT_EINST_NOR_GASART:ua.Int32 = 0
    LT_EINST_NOR_GASDRUCK:ua.Double = 0
    LT_EINST_SAN_ZEIT:ua.Double = 0
    LT_EINST_SAN_RAMPNR:ua.Int32 = 0
    LT_EINST_SAN_DUESENABST:ua.Double = 0
    LT_EINST_SAN_AUSBLASZEIT:ua.Double = 0
    LT_EINST_SAN_GASART:ua.Int32 = 0
    LT_EINST_SAN_GASDRUCK:ua.Double = 0
    LT_SCH_GR_FOKUSLAGE:ua.Double = 0
    LT_SCH_MI_FOKUSLAGE:ua.Double = 0
    LT_SCH_KL_FOKUSLAGE:ua.Double = 0
    LT_SCH_BESCHL_HOCH:ua.Double = 0
    LT_EINST_STRAHL_DM:ua.Double = 0
    LT_LLS_V_OG_2:ua.Double = 0
    LT_LLS_V_OG_LSTG_2:ua.Int32 = 0
    LT_LLS_V_UG_2:ua.Double = 0
    LT_LLS_V_UG_LSTG_2:ua.Int32 = 0
    LT_LFS_V_OG_2:ua.Double = 0
    LT_LFS_V_OG_FREQ_2:ua.Int32 = 0
    LT_LFS_V_UG_2:ua.Double = 0
    LT_LFS_V_UG_FREQ_2:ua.Int32 = 0
    LT_EINST_SAN_FOKUSLAGE:ua.Double = 0
    LT_SON_BESCHL:ua.Double = 0
    LT_EINST_NOR_FOKUSLAGE_PCS:ua.Double = 0
    LT_EINST_NOR_ZEIT_PCS:ua.Double = 0
    LT_EINST_NOR_RAMPNR_PCS:ua.Int32 = 0
    LT_EINST_NOR_DUESENABST_PCS:ua.Double = 0
    LT_EINST_NOR_AUSBLASZEIT_PCS:ua.Double = 0
    LT_EINST_NOR_GASART_PCS:ua.Int32 = 0
    LT_EINST_NOR_GASDRUCK_PCS:ua.Double = 0
    LT_EINST_NOR_OEL_SPRUEH_PCS:ua.Int32 = 0
    LT_EINST_NOR_SENSORIK_PCS:ua.Int32 = 0
    LT_EINST_NOR_QUERBLASEN_PCS:ua.Int32 = 0
    LT_EINST_SAN_FOKUSLAGE_PCS:ua.Double = 0
    LT_EINST_SAN_ZEIT_PCS:ua.Double = 0
    LT_EINST_SAN_RAMPNR_PCS:ua.Int32 = 0
    LT_EINST_SAN_DUESENABST_PCS:ua.Double = 0
    LT_EINST_SAN_AUSBLASZEIT_PCS:ua.Double = 0
    LT_EINST_SAN_GASART_PCS:ua.Int32 = 0
    LT_EINST_SAN_GASDRUCK_PCS:ua.Double = 0
    LT_EINST_SAN_OEL_SPRUEH_PCS:ua.Int32 = 0
    LT_EINST_SAN_SENSORIK_PCS:ua.Int32 = 0
    LT_PARENT:ua.CharArray = b''
    LaserHeadType:ua.Int32 = 0
    LaserHeadGeneration:ua.Int32 = 0
    LaserHeadComponentId:ua.Int32 = 0
    LensFocalLengthMetric:ua.Int32 = 0
    LTSLModeMiddleContour:ua.Int32 = 0
    LT2_VIEWER_NAME:ua.CharArray = b''
    LT2_DIMENSION_MACHINE_MIN:ua.Int32 = 0
    LT2_DIMENSION_MACHINE_MAX:ua.Int32 = 0
    LT2_WERKSTOFF:ua.CharArray = b''
    LT2_LASERTYP:ua.CharArray = b''
    LT2_SUITABLE_FOR_COATING:ua.Int32 = 0
    LT2_PROCESSING_TECHNOLOGY_1:ua.Int32 = 0
    LT2_PROCESSING_TECHNOLOGY_2:ua.Int32 = 0
    LT2_SCH_KL_RED_FOKUSLAGE:ua.Double = 0
    LT2_SCH_GR_FOKUS_DM:ua.Int32 = 0
    LT2_SCH_MI_FOKUS_DM:ua.Int32 = 0
    LT2_SCH_KL_FOKUS_DM:ua.Int32 = 0
    LT2_EINST_NOR_FOKUS_DM_PCS:ua.Int32 = 0
    LT2_EINST_SAN_FOKUS_DM_PCS:ua.Int32 = 0
    LT2_EINST_SAN_QUERBLASDRUCK_PCS:ua.Double = 0
    LT2_EINST_NOR_QUERBLASDRUCK_PCS:ua.Double = 0
    LT2_FiberOpticCableDiameter:ua.Int32 = 0
    LT2_PulsePowerSmallNor:ua.Int32 = 0
    LT2_PulsePowerLargeNor:ua.Int32 = 0
    LTBC_Mode:ua.Int32 = 0
    LT2_Variant:ua.Int32 = 0
    LT2_EINST_NOR_FOKUS_DM:ua.Int32 = 0
    LT2_EINST_SAN_FOKUS_DM:ua.Int32 = 0
    LT2_Material_Internal_Code:ua.Int32 = 0
    LT2_FiberOpticCableCladdingDiameter:ua.Int32 = 0
    LT2_EINST_SAN_MODUS_PCS:ua.Int32 = 0
    LT2_EINST_SAN_FOKUSLAGE_PCS_2:ua.Double = 0
    LT2_EINST_SAN_FOKUS_DM_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_ZEIT_PCS_2:ua.Double = 0
    LT2_EINST_SAN_RAMPNR_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_DUESENABST_PCS_2:ua.Double = 0
    LT2_EINST_SAN_AUSBLASZEIT_PCS_2:ua.Double = 0
    LT2_EINST_SAN_GASART_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_GASDRUCK_PCS_2:ua.Double = 0
    LT2_EINST_SAN_OEL_SPRUEH_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_SENSORIK_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_QUERBLASEN_PCS_2:ua.Int32 = 0
    LT2_EINST_SAN_QUERBLASDRUCK_PCS_2:ua.Double = 0
    LT2_EINST_SAN_FOKUSLAGE_PCS_3:ua.Double = 0
    LT2_EINST_SAN_FOKUS_DM_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_ZEIT_PCS_3:ua.Double = 0
    LT2_EINST_SAN_RAMPNR_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_DUESENABST_PCS_3:ua.Double = 0
    LT2_EINST_SAN_AUSBLASZEIT_PCS_3:ua.Double = 0
    LT2_EINST_SAN_GASART_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_GASDRUCK_PCS_3:ua.Double = 0
    LT2_EINST_SAN_OEL_SPRUEH_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_SENSORIK_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_QUERBLASEN_PCS_3:ua.Int32 = 0
    LT2_EINST_SAN_QUERBLASDRUCK_PCS_3:ua.Double = 0
    LT2_EINST_SAN_QUERBLASEN_PCS_1:ua.Int32 = 0
    LT2_EINST_NOR_MODUS_PCS:ua.Int32 = 0
    LT2_PatchVersion:ua.CharArray = b''
    LT2_NumericalAperture:ua.Int32 = 0
    LT2_LLS_V_UG_3:ua.Double = 0
    LT2_LLS_V_UG_LSTG_3:ua.Double = 0
    LT2_LFS_V_UG_3:ua.Double = 0
    LT2_LFS_V_UG_FREQ_3:ua.Double = 0
    LT2_SCH_PMS_SCHWELLE_FKL:ua.Double = 0
    LT2_SCH_GR_PMS_EIN_FKL:ua.Int32 = 0
    LT2_EINST_NOR_FOKUSLAGE_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_ZEIT_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_RAMPNR_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_DUESENABST_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_AUSBLASZEIT_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_GASART_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_GASDRUCK_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_OEL_SPRUEH_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_SENSORIK_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_QUERBLASEN_PCS_SCHNELL:ua.Int32 = 0
    LT2_EINST_NOR_FOKUS_DM_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_QUERBLASDRUCK_PCS_SCHNELL:ua.Double = 0
    LT2_EINST_NOR_MODUS_PCS_SCHNELL:ua.Int32 = 0



@dataclass
class TsLaserWeldingTechnology:

    '''
    TsLaserWeldingTechnology structure autogenerated from xml
    '''

    ViewerName:ua.CharArray = b''
    CustomerTable:ua.Int32 = 0
    GroupName:ua.CharArray = b''
    WeldingDepth:ua.Double = 0
    NozzleDistance:ua.Double = 0
    LaserName:ua.CharArray = b''
    LaserNominalPower:ua.Int32 = 0
    MaterialName:ua.CharArray = b''
    FocusDistance:ua.Double = 0
    FocalMirrorType:ua.Int32 = 0
    FocalMirrorFocalLength:ua.Int32 = 0
    RedirectionMirrorAngle:ua.Double = 0
    RedirectionMirrorType:ua.Int32 = 0
    GeneralPreHeatingPower:ua.Int32 = 0
    GeneralPreHeatingTime:ua.Double = 0
    GeneralAcceleration:ua.Double = 0
    GeneralWayCorrection:ua.Double = 0
    GeneralPreStreamTimeCrossjet:ua.Double = 0
    GeneralPreStreamTimeGas:ua.Double = 0
    GeneralAfterStreamTimeGas:ua.Double = 0
    GeneralLaserAmplitude:ua.Int32 = 0
    FiberOpticCableDiameter:ua.Double = 0
    LaserType:ua.CharArray = b''
    ParentViewerName:ua.CharArray = b''
    ParentKeyPart:ua.CharArray = b''
    RedirectionMirrorSpotDistance:ua.Double = 0
    Contour1LaserPower:ua.Int32 = 0
    Contour1Feed:ua.Double = 0
    Contour1SamplingRate:ua.Int32 = 0
    Contour1FocalPosition:ua.Double = 0
    Contour1Note:ua.CharArray = b''
    Contour1GasFlowGasId1:ua.Int32 = 0
    Contour1GasFlowAmount1:ua.Double = 0
    Contour1GasFlowGasId2:ua.Int32 = 0
    Contour1GasFlowAmount2:ua.Double = 0
    Contour1GasFlowGasId3:ua.Int32 = 0
    Contour1GasFlowAmount3:ua.Double = 0
    Contour1GasFlowGasId4:ua.Int32 = 0
    Contour1GasFlowAmount4:ua.Double = 0
    Contour1StartRampPower:ua.Int32 = 0
    Contour1EndRampPower:ua.Int32 = 0
    Contour1WireFeed:ua.Double = 0
    Contour1WireRetreat:ua.Double = 0
    Contour1FocalDiameter:ua.Double = 0
    Contour2LaserPower:ua.Int32 = 0
    Contour2Feed:ua.Double = 0
    Contour2SamplingRate:ua.Int32 = 0
    Contour2FocalPosition:ua.Double = 0
    Contour2Note:ua.CharArray = b''
    Contour2GasFlowGasId1:ua.Int32 = 0
    Contour2GasFlowAmount1:ua.Double = 0
    Contour2GasFlowGasId2:ua.Int32 = 0
    Contour2GasFlowAmount2:ua.Double = 0
    Contour2GasFlowGasId3:ua.Int32 = 0
    Contour2GasFlowAmount3:ua.Double = 0
    Contour2GasFlowGasId4:ua.Int32 = 0
    Contour2GasFlowAmount4:ua.Double = 0
    Contour2StartRampPower:ua.Int32 = 0
    Contour2EndRampPower:ua.Int32 = 0
    Contour2WireFeed:ua.Double = 0
    Contour2WireRetreat:ua.Double = 0
    Contour2FocalDiameter:ua.Double = 0
    Contour3LaserPower:ua.Int32 = 0
    Contour3Feed:ua.Double = 0
    Contour3SamplingRate:ua.Int32 = 0
    Contour3FocalPosition:ua.Double = 0
    Contour3Note:ua.CharArray = b''
    Contour3GasFlowGasId1:ua.Int32 = 0
    Contour3GasFlowAmount1:ua.Double = 0
    Contour3GasFlowGasId2:ua.Int32 = 0
    Contour3GasFlowAmount2:ua.Double = 0
    Contour3GasFlowGasId3:ua.Int32 = 0
    Contour3GasFlowAmount3:ua.Double = 0
    Contour3GasFlowGasId4:ua.Int32 = 0
    Contour3GasFlowAmount4:ua.Double = 0
    Contour3StartRampPower:ua.Int32 = 0
    Contour3EndRampPower:ua.Int32 = 0
    Contour3WireFeed:ua.Double = 0
    Contour3WireRetreat:ua.Double = 0
    Contour3FocalDiameter:ua.Double = 0
    Contour4LaserPower:ua.Int32 = 0
    Contour4Feed:ua.Double = 0
    Contour4SamplingRate:ua.Int32 = 0
    Contour4FocalPosition:ua.Double = 0
    Contour4Note:ua.CharArray = b''
    Contour4GasFlowGasId1:ua.Int32 = 0
    Contour4GasFlowAmount1:ua.Double = 0
    Contour4GasFlowGasId2:ua.Int32 = 0
    Contour4GasFlowAmount2:ua.Double = 0
    Contour4GasFlowGasId3:ua.Int32 = 0
    Contour4GasFlowAmount3:ua.Double = 0
    Contour4GasFlowGasId4:ua.Int32 = 0
    Contour4GasFlowAmount4:ua.Double = 0
    Contour4StartRampPower:ua.Int32 = 0
    Contour4EndRampPower:ua.Int32 = 0
    Contour4WireFeed:ua.Double = 0
    Contour4WireRetreat:ua.Double = 0
    Contour4FocalDiameter:ua.Double = 0
    MarkingLaserPower:ua.Int32 = 0
    MarkingFeed:ua.Double = 0
    MarkingSamplingRate:ua.Int32 = 0
    MarkingFocalPosition:ua.Double = 0
    MarkingNote:ua.CharArray = b''
    MarkingGasFlowGasId1:ua.Int32 = 0
    MarkingGasFlowAmount1:ua.Double = 0
    MarkingGasFlowGasId2:ua.Int32 = 0
    MarkingGasFlowAmount2:ua.Double = 0
    MarkingGasFlowGasId3:ua.Int32 = 0
    MarkingGasFlowAmount3:ua.Double = 0
    MarkingGasFlowGasId4:ua.Int32 = 0
    MarkingGasFlowAmount4:ua.Double = 0
    MarkingFocalDiameter:ua.Double = 0
    Contour5LaserPower:ua.Int32 = 0
    Contour5Feed:ua.Double = 0
    Contour5SamplingRate:ua.Int32 = 0
    Contour5FocalPosition:ua.Double = 0
    Contour5Note:ua.CharArray = b''
    Contour5GasFlowGasId1:ua.Int32 = 0
    Contour5GasFlowAmount1:ua.Double = 0
    Contour5GasFlowGasId2:ua.Int32 = 0
    Contour5GasFlowAmount2:ua.Double = 0
    Contour5GasFlowGasId3:ua.Int32 = 0
    Contour5GasFlowAmount3:ua.Double = 0
    Contour5GasFlowGasId4:ua.Int32 = 0
    Contour5GasFlowAmount4:ua.Double = 0
    Contour5StartRampPower:ua.Int32 = 0
    Contour5EndRampPower:ua.Int32 = 0
    Contour5FocalDiameter:ua.Double = 0
    Contour6LaserPower:ua.Int32 = 0
    Contour6Feed:ua.Double = 0
    Contour6SamplingRate:ua.Int32 = 0
    Contour6FocalPosition:ua.Double = 0
    Contour6Note:ua.CharArray = b''
    Contour6GasFlowGasId1:ua.Int32 = 0
    Contour6GasFlowAmount1:ua.Double = 0
    Contour6GasFlowGasId2:ua.Int32 = 0
    Contour6GasFlowAmount2:ua.Double = 0
    Contour6GasFlowGasId3:ua.Int32 = 0
    Contour6GasFlowAmount3:ua.Double = 0
    Contour6GasFlowGasId4:ua.Int32 = 0
    Contour6GasFlowAmount4:ua.Double = 0
    Contour6StartRampPower:ua.Int32 = 0
    Contour6EndRampPower:ua.Int32 = 0
    Contour6FocalDiameter:ua.Double = 0
    AWSActive:ua.Int32 = 0
    AWSPoint1Speed:ua.Double = 0
    AWSPoint1LaserPower:ua.Int32 = 0
    AWSPoint2Speed:ua.Double = 0
    AWSPoint2LaserPower:ua.Int32 = 0
    AWSPoint3Speed:ua.Double = 0
    AWSPoint3LaserPower:ua.Int32 = 0
    AWSPoint4Speed:ua.Double = 0
    AWSPoint4LaserPower:ua.Int32 = 0
    AWSPoint5Speed:ua.Double = 0
    AWSPoint5LaserPower:ua.Int32 = 0
    AWSPoint6Speed:ua.Double = 0
    AWSPoint6LaserPower:ua.Int32 = 0
    Forming:ua.Int32 = 0
    FormingPreStreamTime:ua.Double = 0
    FormingAfterStreamTime:ua.Double = 0
    FormingGasFlowGasId1:ua.Int32 = 0
    FormingGasFlowAmount1:ua.Double = 0
    FormingGasFlowGasId2:ua.Int32 = 0
    FormingGasFlowAmount2:ua.Double = 0
    FormingGasFlowGasId3:ua.Int32 = 0
    FormingGasFlowAmount3:ua.Double = 0
    FormingGasFlowGasId4:ua.Int32 = 0
    FormingGasFlowAmount4:ua.Double = 0
    WireMaterialName:ua.CharArray = b''
    WireDiameter:ua.Double = 0
    WireLaserPower:ua.Int32 = 0
    WireCycleTime:ua.Double = 0
    WireSamplingRate:ua.Int32 = 0
    LaserPulseMode:ua.Int32 = 0
    LaserProgramNumber:ua.Int32 = 0
    LaserSupportsPulseModePMP:ua.Int32 = 0
    LaserSupportsPulseModePFP:ua.Int32 = 0
    Contour1PulseAmplitude:ua.Int32 = 0
    Contour1PulseDuration:ua.Double = 0
    Contour1PulseSamplingRate:ua.Double = 0
    Contour1StartRampPulseAmplitude:ua.Int32 = 0
    Contour1EndRampPulseAmplitude:ua.Int32 = 0
    Contour2PulseAmplitude:ua.Int32 = 0
    Contour2PulseDuration:ua.Double = 0
    Contour2PulseSamplingRate:ua.Double = 0
    Contour2StartRampPulseAmplitude:ua.Int32 = 0
    Contour2EndRampPulseAmplitude:ua.Int32 = 0
    Contour3PulseAmplitude:ua.Int32 = 0
    Contour3PulseDuration:ua.Double = 0
    Contour3PulseSamplingRate:ua.Double = 0
    Contour3StartRampPulseAmplitude:ua.Int32 = 0
    Contour3EndRampPulseAmplitude:ua.Int32 = 0
    Contour4PulseAmplitude:ua.Int32 = 0
    Contour4PulseDuration:ua.Double = 0
    Contour4PulseSamplingRate:ua.Double = 0
    Contour4StartRampPulseAmplitude:ua.Int32 = 0
    Contour4EndRampPulseAmplitude:ua.Int32 = 0
    MarkingPulseAmplitude:ua.Int32 = 0
    MarkingPulseDuration:ua.Double = 0
    MarkingPulseSamplingRate:ua.Double = 0
    Contour5PulseAmplitude:ua.Int32 = 0
    Contour5PulseDuration:ua.Double = 0
    Contour5PulseSamplingRate:ua.Double = 0
    Contour5StartRampPulseAmplitude:ua.Int32 = 0
    Contour5EndRampPulseAmplitude:ua.Int32 = 0
    Contour6PulseAmplitude:ua.Int32 = 0
    Contour6PulseDuration:ua.Double = 0
    Contour6PulseSamplingRate:ua.Double = 0
    Contour6StartRampPulseAmplitude:ua.Int32 = 0
    Contour6EndRampPulseAmplitude:ua.Int32 = 0
    AWSPulseSpeed1:ua.Double = 0
    AWSPulseSpeed2:ua.Double = 0
    AWSPulseSpeed3:ua.Double = 0
    AWSPulseSpeed4:ua.Double = 0
    AWSPulseSpeed5:ua.Double = 0
    AWSPulseSpeed6:ua.Double = 0
    AWSPulseAmplitude1:ua.Int32 = 0
    AWSPulseAmplitude2:ua.Int32 = 0
    AWSPulseAmplitude3:ua.Int32 = 0
    AWSPulseAmplitude4:ua.Int32 = 0
    AWSPulseAmplitude5:ua.Int32 = 0
    AWSPulseAmplitude6:ua.Int32 = 0
    AWSPulseSamplingRate1:ua.Double = 0
    AWSPulseSamplingRate2:ua.Double = 0
    AWSPulseSamplingRate3:ua.Double = 0
    AWSPulseSamplingRate4:ua.Double = 0
    AWSPulseSamplingRate5:ua.Double = 0
    AWSPulseSamplingRate6:ua.Double = 0
    WirePulseLaserAmplitude:ua.Int32 = 0
    WirePulseDuration:ua.Double = 0
    WirePulseSamplingRate:ua.Double = 0



@dataclass
class TsMachineMessage:

    '''
    TsMachineMessage structure autogenerated from xml
    '''

    EventTime:ua.DateTime = datetime.utcnow()
    Number:ua.Int32 = 0
    Text:ua.CharArray = b''



@dataclass
class TsMonitoredProperty:

    '''
    TsMonitoredProperty structure autogenerated from xml
    '''

    IsAvailable:ua.Boolean = True
    QualityValue:ua.Byte = 0



@dataclass
class TsMonitoredPropertyWithRawValue:

    '''
    TsMonitoredPropertyWithRawValue structure autogenerated from xml
    '''

    IsAvailable:ua.Boolean = True
    QualityValue:ua.Byte = 0
    Value:ua.Int32 = 0



@dataclass
class TsPartSeparationInfoRequest:

    '''
    TsPartSeparationInfoRequest structure autogenerated from xml
    '''

    ProductionPackageName:ua.CharArray = b''
    ProductionOrderIdentifier:ua.CharArray = b''
    Name:ua.CharArray = b''
    CurrentQuantity:ua.UInt32 = 0



@dataclass
class TsPartSeparationPart:

    '''
    TsPartSeparationPart structure autogenerated from xml
    '''

    PartSequenceID:ua.Int32 = 0
    PartSeparationState:ua.TePartSeparationState = ua.TePartSeparationState(4)
    MarkerColor:ua.CharArray = b''
    PartStatusNote:ua.CharArray = b''
    LogisticCarrierReference:ua.CharArray = b''
    PartSeparationDuration:ua.Int32 = 0

Failed to execute auto-generated code from UA datatype:

@dataclass
class TsPartSeparationPart:

    '''
    TsPartSeparationPart structure autogenerated from xml
    '''

    PartSequenceID:ua.Int32 = 0
    PartSeparationState:ua.TePartSeparationState = ua.TePartSeparationState(4)
    MarkerColor:ua.CharArray = b''
    PartStatusNote:ua.CharArray = b''
    LogisticCarrierReference:ua.CharArray = b''
    PartSeparationDuration:ua.Int32 = 0
Traceback (most recent call last):
  File "C:\Users\mundjoh\AppData\Roaming\Python\Python38\site-packages\asyncua\common\structures.py", line 281, in _generate_python_class
    exec(code, env)
  File "<string>", line 4, in <module>
  File "<string>", line 11, in TsPartSeparationPart
AttributeError: module 'asyncua.ua' has no attribute 'TePartSeparationState'
Traceback (most recent call last):
  File ".\PythonMachineDemoServer.py", line 243, in <module>
    asyncio.run(main())
  File "C:\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File ".\PythonMachineDemoServer.py", line 184, in main
    await server.load_type_definitions()
  File "C:\Users\mundjoh\AppData\Roaming\Python\Python38\site-packages\asyncua\server\server.py", line 649, in load_type_definitions
    return await load_type_definitions(self, nodes)
  File "C:\Users\mundjoh\AppData\Roaming\Python\Python38\site-packages\asyncua\common\structures.py", line 223, in load_type_definitions
    generator.get_python_classes(structs_dict)
  File "C:\Users\mundjoh\AppData\Roaming\Python\Python38\site-packages\asyncua\common\structures.py", line 177, in get_python_classes
    return _generate_python_class(self.model, env=env)
  File "C:\Users\mundjoh\AppData\Roaming\Python\Python38\site-packages\asyncua\common\structures.py", line 281, in _generate_python_class
    exec(code, env)
  File "<string>", line 4, in <module>
  File "<string>", line 11, in TsPartSeparationPart
AttributeError: module 'asyncua.ua' has no attribute 'TePartSeparationState'
```

**Comment by HeikoS-Trumpf** [comment]
Thanks for reporting. Fixed in main and tested with v0.9.92. 
There were several incompatible changes in the library.
